// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH0iFMa8Kp4iuKTdYTyGl2L5mq9huQZ5Y',
    appId: '1:1072690535614:web:7719b70812f0facc4dd2ef',
    messagingSenderId: '1072690535614',
    projectId: 'fir-complete-85396',
    authDomain: 'fir-complete-85396.firebaseapp.com',
    storageBucket: 'fir-complete-85396.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSuKaFu2udOFvW_M-w0o56XaDJztFuWjs',
    appId: '1:1072690535614:android:5468efa30ad0d58d4dd2ef',
    messagingSenderId: '1072690535614',
    projectId: 'fir-complete-85396',
    storageBucket: 'fir-complete-85396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCbdfXFC_3p48z5F9dcxgtep0I64JAUQ',
    appId: '1:1072690535614:ios:8588ffbd3964b8ce4dd2ef',
    messagingSenderId: '1072690535614',
    projectId: 'fir-complete-85396',
    storageBucket: 'fir-complete-85396.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCbdfXFC_3p48z5F9dcxgtep0I64JAUQ',
    appId: '1:1072690535614:ios:8588ffbd3964b8ce4dd2ef',
    messagingSenderId: '1072690535614',
    projectId: 'fir-complete-85396',
    storageBucket: 'fir-complete-85396.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH0iFMa8Kp4iuKTdYTyGl2L5mq9huQZ5Y',
    appId: '1:1072690535614:web:11baf178ee08bafa4dd2ef',
    messagingSenderId: '1072690535614',
    projectId: 'fir-complete-85396',
    authDomain: 'fir-complete-85396.firebaseapp.com',
    storageBucket: 'fir-complete-85396.firebasestorage.app',
  );
}