// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8w3FHz9AuaQ8mxl_9oTaK8y3RkTHcsec',
    appId: '1:846093366869:web:34fe10c93e4583562e86dc',
    messagingSenderId: '846093366869',
    projectId: 'otpverify-529dd',
    authDomain: 'otpverify-529dd.firebaseapp.com',
    storageBucket: 'otpverify-529dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBenVzuQG6aPUmvEp2IsEnYPyStPWUAVh0',
    appId: '1:846093366869:android:ec05459f1ab8d6632e86dc',
    messagingSenderId: '846093366869',
    projectId: 'otpverify-529dd',
    storageBucket: 'otpverify-529dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtWMeyessQ01_u8IAHsa1Meo_bNeFmZho',
    appId: '1:846093366869:ios:91c1fc79785e487e2e86dc',
    messagingSenderId: '846093366869',
    projectId: 'otpverify-529dd',
    storageBucket: 'otpverify-529dd.firebasestorage.app',
    iosBundleId: 'com.example.usersVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtWMeyessQ01_u8IAHsa1Meo_bNeFmZho',
    appId: '1:846093366869:ios:91c1fc79785e487e2e86dc',
    messagingSenderId: '846093366869',
    projectId: 'otpverify-529dd',
    storageBucket: 'otpverify-529dd.firebasestorage.app',
    iosBundleId: 'com.example.usersVerification',
  );
}
